apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: webapp
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8000 # The port the service listens on
    targetPort: 8000
