apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: webapp
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306 # The port that the service will expose
    targetPort: 3306 # The port on the pod where MySQL is listening
